spring:
  application:
    name: t1-school-learn
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: pass
    initialization:
      mode: always
      continue-on-error: false
      platform: postgresql
      data: classpath:data.sql
