CREATE TABLE IF NOT EXISTS tasks
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    user_id     BIGINT
);


INSERT INTO tasks (title, description, user_id)
VALUES ('Задача 1', 'Описание задачи 1', 101),
       ('Задача 2', 'Описание задачи 2', 102),
       ('Задача 3', 'Описание задачи 3', 103),
       ('Задача 4', 'Описание задачи 4', 104),
       ('Задача 5', 'Описание задачи 5', 105);